export type ProfileType = "tech" | "business";

export interface Profile {
  id: string;
  type: ProfileType;
  name: string;
  role: string;
  avatar: string;
  photo?: string;
  location: string;
  bio: string;
  bullets: [string, string, string];
  skills: string[];
  agencyName?: string;
  agencyDescription?: string;
  agencyStage?: string;
  lookingFor: string;
  linkedin?: string;
  website?: string;
  isVerified: boolean;
}

export const fakeProfiles: Profile[] = [
  {
    id: "1",
    type: "tech",
    name: "Thomas R.",
    role: "Fondateur Tech",
    avatar: "TR",
    photo: "/avatars/maxime.png",
    location: "Paris, France",
    bio: "Spécialiste IA générative, ex-lead IA chez une startup Series B. J'ai déployé des agents LLM en production pour 5 entreprises. Je cherche un associé business pour lancer mon agence d'automatisation IA.",
    bullets: [
      "5 agents IA en prod — GPT-4, Claude, Gemini API maîtrisés",
      "RAG + fine-tuning livrés pour 3 clients PME en 6 mois",
      "Anthropic Certified Developer + AWS ML Specialty",
    ],
    skills: ["IA Générative", "LangChain", "RAG", "Agents IA", "OpenAI API", "Fine-tuning"],
    agencyName: "NeuraFlow",
    agencyDescription: "Automatisation des processus métier par l'IA pour les ETI françaises",
    agencyStage: "MVP en cours",
    lookingFor: "Un profil commercial avec réseau dans les ETI/PME pour développer les ventes et structurer l'offre.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "2",
    type: "business",
    name: "Sophie M.",
    role: "Fondatrice Business",
    avatar: "SM",
    photo: "/avatars/sophie.png",
    location: "Paris, France",
    bio: "Fondatrice d'une SMMA à 23 ans, revenue à 30k€/mois en 14 mois. Experte en acquisition client et cold outreach. Je cherche un associé tech pour automatiser mes process et scaler avec l'IA.",
    bullets: [
      "SMMA lancée à 23 ans — 30k€/mois en 14 mois",
      "500+ cold calls, 80+ clients signés en 2 ans",
      "Réseau de 40 dirigeants PME activables maintenant",
    ],
    skills: ["SMMA", "Cold Outreach", "Closing B2B", "Growth", "Acquisition"],
    agencyName: "ScaleAI Agency",
    agencyDescription: "Agence IA d'acquisition et d'automatisation pour PME",
    agencyStage: "Idée / recherche d'associé",
    lookingFor: "Un profil tech pour automatiser les workflows d'acquisition et construire des outils IA sur-mesure.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "3",
    type: "tech",
    name: "Enzo D.",
    role: "Fondateur Tech",
    avatar: "ED",
    photo: "/avatars/karim.png",
    location: "Bordeaux, France",
    bio: "Expert automatisation n8n & Make, 3 ans freelance. J'ai automatisé les ops de 20+ PME avec des workflows IA. Je cherche un associé commercial pour lancer une agence d'automatisation IA.",
    bullets: [
      "20+ PME automatisées — 200h/mois économisées en moyenne",
      "Maîtrise n8n, Make, Zapier + intégrations LLM custom",
      "n8n Certified Expert — Partner officiel",
    ],
    skills: ["n8n", "Make", "Automatisation", "Agents IA", "Zapier", "API Integration"],
    agencyName: "AutoFlow AI",
    agencyDescription: "Automatisation des workflows métier par agents IA pour PME",
    agencyStage: "Premiers clients",
    lookingFor: "Un associé business pour signer les premiers contrats et structurer l'offre commerciale.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "4",
    type: "business",
    name: "Amélie F.",
    role: "Fondatrice Business",
    avatar: "AF",
    photo: "/avatars/thomas.png",
    location: "Lyon, France",
    bio: "Ex-commerciale SaaS B2B, 3 ans à closer des deals entre 5k et 50k€. J'ai lancé ma propre agence marketing digital à 25 ans. Je cherche un associé tech pour pivoter vers l'IA.",
    bullets: [
      "Closer SaaS B2B — 120k€ de CA solo en 12 mois",
      "Agence marketing lancée à 25 ans, 15 clients actifs",
      "300+ cold emails/semaine, taux de réponse 18%",
    ],
    skills: ["SaaS Sales", "Cold Email", "Négociation", "Marketing Digital", "B2B"],
    agencyName: "Amplify AI",
    agencyDescription: "Automatisation marketing et acquisition par l'IA",
    agencyStage: "MVP en cours",
    lookingFor: "Un dev IA pour automatiser les campagnes d'outreach et construire des agents de prospection.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "5",
    type: "tech",
    name: "Lucas D.",
    role: "Fondateur Tech",
    avatar: "LD",
    photo: "/avatars/lucas.png",
    location: "Toulouse, France",
    bio: "Doctorat en IA à l'INRIA, 5 ans de recherche en vision par ordinateur et multimodal. J'ai publié dans NeurIPS et ICLR. Je veux quitter la recherche pour créer une agence IA appliquée à l'industrie.",
    bullets: [
      "Doctorat IA INRIA — 4 publications NeurIPS et ICLR, spécialiste Computer Vision",
      "3 projets POC livrés en industrie (défaut qualité, contrôle visuel, robotique)",
      "Maîtrise PyTorch, Hugging Face, MLOps — pipeline prod complet",
    ],
    skills: ["Computer Vision", "PyTorch", "Multimodal AI", "MLOps", "Hugging Face", "Python"],
    agencyStage: "Idée / en exploration",
    lookingFor: "Un profil business avec une expérience dans l'industrie manufacturière ou logistique pour trouver et signer les premiers clients.",
    isVerified: true,
  },
  {
    id: "6",
    type: "business",
    name: "Maxime L.",
    role: "Fondateur Business",
    avatar: "ML",
    location: "Bordeaux, France",
    bio: "Freelance en prospection B2B depuis 3 ans, spécialisé cold call et LinkedIn outreach. J'ai généré +200k€ de pipeline pour mes clients. Je veux créer une agence IA d'acquisition avec un associé tech.",
    bullets: [
      "200k€ de pipeline généré en prospection B2B pure",
      "1 200+ cold calls effectués, 22% de taux de RDV",
      "Réseau de 60 décideurs PME/ETI signables rapidement",
    ],
    skills: ["Cold Call", "LinkedIn Outreach", "Pipeline B2B", "Closing", "Négociation"],
    agencyName: "LeadAI",
    agencyDescription: "Agence d'acquisition client automatisée par l'IA",
    agencyStage: "Idée / recherche d'associé",
    lookingFor: "Un dev IA pour construire des agents de prospection autonomes et automatiser le suivi commercial.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "7",
    type: "tech",
    name: "Inès M.",
    role: "Fondatrice Tech",
    avatar: "IM",
    photo: "/avatars/amelie.png",
    location: "Montpellier, France",
    bio: "Data Scientist senior chez BNP Paribas pendant 5 ans. Spécialiste en IA pour la finance (scoring, détection de fraude, prévision). Je cherche une associée business pour lancer une offre IA dédiée aux fintechs et assurances.",
    bullets: [
      "Data Scientist senior — 5 ans BNP Paribas, IA scoring et détection de fraude",
      "2 modèles ML déployés en production pour +2M de clients bancaires",
      "Certifiée AWS ML Specialty + Azure Data Scientist Associate",
    ],
    skills: ["Data Science", "IA Fintech", "Fraud Detection", "Python", "Power BI", "Azure ML"],
    agencyName: "FinIA Consulting",
    agencyDescription: "Solutions IA pour banques, assurances et fintechs",
    agencyStage: "Premiers clients",
    lookingFor: "Un profil business avec un réseau solide dans la finance ou l'assurance, à l'aise avec des cycles de vente B2B longs.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "8",
    type: "business",
    name: "Romain C.",
    role: "Fondateur Business",
    avatar: "RC",
    location: "Strasbourg, France",
    bio: "Ex-directeur des opérations dans une chaîne de 200 restaurants. J'ai digitalisé entièrement les process de 3 enseignes. Je vois comment l'IA peut révolutionner la restauration et l'hôtellerie.",
    bullets: [
      "Ex-directeur Ops — 200 restaurants managés, 3 enseignes digitalisées de A à Z",
      "Réseau de 40+ directeurs de chaînes HoReCa et franchise France",
      "-18% de coûts opérationnels obtenus sur la dernière enseigne gérée",
    ],
    skills: ["Ops Management", "Partenariats B2B", "Retail", "Restauration", "Franchise"],
    agencyStage: "Idée / recherche d'associé",
    lookingFor: "Un développeur IA capable de créer des solutions d'optimisation des stocks, menus et staffing pour le secteur HoReCa.",
    isVerified: true,
  },
  {
    id: "9",
    type: "tech",
    name: "Adrien P.",
    role: "Fondateur Tech",
    avatar: "AP",
    location: "Lille, France",
    bio: "Lead dev backend 7 ans, passionné d'automatisation. J'ai déployé des agents IA autonomes pour automatiser des workflows complexes en entreprise. Maîtrise parfaite de n8n, Make et des architectures multi-agents.",
    bullets: [
      "Lead dev backend 7 ans — spécialiste agents IA et automatisation n8n/LangGraph",
      "15 workflows d'automatisation déployés chez des clients, 200h/mois économisées",
      "Formation Make Advanced + certifié n8n Expert Partner",
    ],
    skills: ["Agents IA", "n8n", "Make/Zapier", "API Integration", "Automation", "LangGraph"],
    agencyName: "AutoFlow",
    agencyDescription: "Automatisation des workflows par agents IA",
    agencyStage: "Premiers clients",
    lookingFor: "Un commercial ou business developer pour closer les prospects. J'ai des démos très convaincantes, il faut quelqu'un pour amener les leads.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "10",
    type: "business",
    name: "Clara B.",
    role: "Fondatrice Business",
    avatar: "CB",
    location: "Paris, France",
    bio: "Avocate reconvertie en entrepreneur, 4 ans dans la LegalTech. J'ai co-fondé un SaaS contractuel vendu à 800k€. Je veux maintenant construire une agence IA spécialisée dans l'automatisation juridique et compliance.",
    bullets: [
      "Avocate reconvertie — co-fondatrice SaaS LegalTech revendu 800k€ en 3 ans",
      "Réseau de 60+ cabinets d'avocats et directions juridiques grands comptes",
      "+45% de taux de conversion obtenu sur le pipeline commercial LegalTech",
    ],
    skills: ["Droit des affaires", "LegalTech", "Business Development", "SaaS", "Fundraising"],
    agencyName: "LexIA",
    agencyDescription: "Automatisation juridique et compliance par l'IA",
    agencyStage: "Pré-seed / amorçage",
    lookingFor: "Un ingénieur IA avec expérience en NLP et traitement de documents légaux (contrats, réglementations).",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "11",
    type: "tech",
    name: "Youssef A.",
    role: "Fondateur Tech",
    avatar: "YA",
    location: "Paris, France",
    bio: "CTO de startup pendant 4 ans, full-stack et IA. J'ai construit de A à Z une plateforme SaaS IA utilisée par 500+ entreprises. Expert en architectures scalables et intégration LLMs en production.",
    bullets: [
      "CTO 4 ans — SaaS IA livré de zéro à 500+ entreprises clientes",
      "Stack complète : LLMs, Next.js, PostgreSQL, Docker, déploiement prod scalable",
      "Formation Stanford ML + certification AWS Solutions Architect",
    ],
    skills: ["CTO Experience", "LLMs", "Next.js", "PostgreSQL", "Docker", "Scalability"],
    agencyName: "BuildAI",
    agencyDescription: "Développement sur-mesure de produits IA pour startups et scale-ups",
    agencyStage: "Actif / cherche associé",
    lookingFor: "Un co-fondateur business avec expérience dans les startups tech pour gérer la croissance et lever des fonds.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "12",
    type: "business",
    name: "Lucie G.",
    role: "Fondatrice Business",
    avatar: "LG",
    location: "Bordeaux, France",
    bio: "10 ans en cabinet de conseil (Capgemini), spécialisée transformation digitale des collectivités et du secteur public. Je vois une opportunité énorme dans l'IA pour le secteur public français.",
    bullets: [
      "10 ans Capgemini — projets à +5M€ pour collectivités et ministères",
      "Réseau de 25+ DSI et élus dans l'écosystème public français",
      "3 appels d'offres remportés seule sur les 6 derniers mois d'activité",
    ],
    skills: ["Secteur Public", "Conseil en transformation", "Appels d'offres", "Gestion de projet"],
    agencyStage: "Idée / en exploration",
    lookingFor: "Un expert IA capable de répondre aux enjeux de souveraineté numérique et de déployer des solutions IA on-premise pour administrations.",
    isVerified: true,
  },
];
