export type ProfileType = "tech" | "business";

export interface Profile {
  id: string;
  type: ProfileType;
  name: string;
  role: string;
  avatar: string;
  photo?: string;
  location: string;
  bio: string;
  bullets: [string, string, string];
  skills: string[];
  agencyName?: string;
  agencyDescription?: string;
  agencyStage?: string;
  lookingFor: string;
  linkedin?: string;
  website?: string;
  isVerified: boolean;
}

export const fakeProfiles: Profile[] = [
  {
    id: "1",
    type: "tech",
    name: "Thomas R.",
    role: "Expert Automatisation",
    avatar: "TR",
    photo: "/avatars/maxime.png",
    location: "Paris · 31 ans",
    bio: "Spécialiste n8n / Make / Zapier, 50+ workflows déployés chez des clients. 3 agences clientes avec ROI démontré sous 30 jours.",
    bullets: [
      "50+ workflows déployés — 3 agences clientes, ROI < 30 jours",
      "Expertise intégrations API, scraping et orchestration de données",
      "n8n Certified Expert — Partner officiel Make",
    ],
    skills: ["n8n", "Make", "Zapier", "API Integration", "Scraping", "Automatisation"],
    agencyName: "FlowStack",
    agencyDescription: "Automatisation des workflows métier pour agences et PME",
    agencyStage: "Premiers clients",
    lookingFor: "Un profil commercial pour signer de nouveaux clients et structurer l’offre.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "2",
    type: "business",
    name: "Sophie M.",
    role: "Closer B2B",
    avatar: "SM",
    photo: "/avatars/sophie.png",
    location: "Paris · 27 ans",
    bio: "Expert outbound — 200k€+ de pipeline généré en prospection pure. 500+ cold calls, 80+ clients signés, taux de closing 25%.",
    bullets: [
      "200k€+ de pipeline généré en outbound pur",
      "500+ cold calls, 80+ clients signés, 25% de closing",
      "Spécialisée vente de services IA/tech à des PME/ETI",
    ],
    skills: ["Cold Call", "Outbound", "Closing B2B", "Prospection", "Vente IA/tech"],
    agencyName: "OutreachAI",
    agencyDescription: "Acquisition et prospection automatisée pour agences IA",
    agencyStage: "Idée / recherche d'associé",
    lookingFor: "Un profil tech pour automatiser la prospection et construire des outils d’outreach IA.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "3",
    type: "tech",
    name: "Enzo M.",
    role: "Développeur Agentique",
    avatar: "EM",
    photo: "/avatars/karim.png",
    location: "Lyon · 28 ans",
    bio: "Architecte systèmes multi-agents (CrewAI, AutoGen, LangGraph, n8n AI). 5 projets agentiques livrés — mémoire persistante, MCP, tool calling.",
    bullets: [
      "5 projets agentiques livrés — mémoire persistante, MCP, tool calling",
      "10+ agents IA en production, temps de traitement réduit de 70%",
      "Maîtrise CrewAI, AutoGen, LangGraph, n8n AI, OpenClaw",
    ],
    skills: ["CrewAI", "AutoGen", "LangGraph", "n8n AI", "Agents IA", "MCP"],
    agencyName: "AgentLab",
    agencyDescription: "Systèmes multi-agents sur-mesure pour automatisation avancée",
    agencyStage: "Premiers clients",
    lookingFor: "Un associé business pour closer les prospects et structurer l’offre commerciale.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "4",
    type: "business",
    name: "Marc D.",
    role: "Ops & Delivery",
    avatar: "MD",
    photo: "/avatars/marc.png",
    location: "Nantes · 34 ans",
    bio: "Ex-consultant — 10+ projets IA livrés, 95% de taux de satisfaction client. Onboarding structuré en 5 jours, churn réduit à moins de 5%.",
    bullets: [
      "10+ projets IA livrés — 95% de satisfaction client",
      "Onboarding structuré en 5 jours, churn < 5%",
      "Pilotage de 3 équipes techniques en simultané",
    ],
    skills: ["Project Management", "Delivery", "Consulting", "Onboarding", "Ops"],
    agencyName: "OpsAI",
    agencyDescription: "Delivery et ops pour agences IA et startups",
    agencyStage: "Actif / cherche associé",
    lookingFor: "Un profil tech pour construire les produits IA que je peux ensuite vendre et livrer.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "5",
    type: "tech",
    name: "Ben D.",
    role: "Vibe Coder / No-Code IA",
    avatar: "BD",
    photo: "/avatars/ben.png",
    location: "Bordeaux · 26 ans",
    bio: "Builder hybride : Cursor, Bolt, Replit — MVP livré en 48h chrono. 2 SaaS IA lancés en solo, premiers clients payants acquis.",
    bullets: [
      "MVP livré en 48h — Cursor, Bolt, Replit maîtrisés",
      "2 SaaS IA en solo, premiers clients payants acquis",
      "Stack Supabase, Vercel, APIs IA — full no/low-code",
    ],
    skills: ["Cursor", "Bolt", "Replit", "Supabase", "Vercel", "No-Code IA"],
    agencyName: "VibeStack",
    agencyDescription: "Prototypage et MVP IA ultra-rapides pour fondateurs",
    agencyStage: "Premiers clients",
    lookingFor: "Un associé business pour commercialiser et scaler les produits.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "6",
    type: "business",
    name: "Amélie F.",
    role: "Growth / Acquisition",
    avatar: "AF",
    photo: "/avatars/amelie_new.png",
    location: "Lyon · 29 ans",
    bio: "Expert content LinkedIn — 10k+ abonnés, 50+ leads entrants/mois. A scalé une offre de 0 à 30k€/mois en 18 mois.",
    bullets: [
      "10k+ abonnés LinkedIn — 50+ leads entrants/mois",
      "Tunnel de vente optimisé — taux de conversion landing 12%",
      "0 → 30k€/mois scalé en 18 mois",
    ],
    skills: ["LinkedIn", "Content Marketing", "Growth", "Acquisition", "Funnel"],
    agencyName: "GrowthAI",
    agencyDescription: "Acquisition organique et funnel automatisé par l'IA",
    agencyStage: "Actif / cherche associé",
    lookingFor: "Un profil tech pour automatiser la création de contenu et le nurturing des leads.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "7",
    type: "tech",
    name: "Inès M.",
    role: "Fondatrice Tech",
    avatar: "IM",
    photo: "/avatars/amelie.png",
    location: "Montpellier, France",
    bio: "Data Scientist senior chez BNP Paribas pendant 5 ans. Spécialiste en IA pour la finance (scoring, détection de fraude, prévision). Je cherche une associée business pour lancer une offre IA dédiée aux fintechs et assurances.",
    bullets: [
      "Data Scientist senior — 5 ans BNP Paribas, IA scoring et détection de fraude",
      "2 modèles ML déployés en production pour +2M de clients bancaires",
      "Certifiée AWS ML Specialty + Azure Data Scientist Associate",
    ],
    skills: ["Data Science", "IA Fintech", "Fraud Detection", "Python", "Power BI", "Azure ML"],
    agencyName: "FinIA Consulting",
    agencyDescription: "Solutions IA pour banques, assurances et fintechs",
    agencyStage: "Premiers clients",
    lookingFor: "Un profil business avec un réseau solide dans la finance ou l'assurance, à l'aise avec des cycles de vente B2B longs.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "8",
    type: "business",
    name: "Romain C.",
    role: "Fondateur Business",
    avatar: "RC",
    location: "Strasbourg, France",
    bio: "Ex-directeur des opérations dans une chaîne de 200 restaurants. J'ai digitalisé entièrement les process de 3 enseignes. Je vois comment l'IA peut révolutionner la restauration et l'hôtellerie.",
    bullets: [
      "Ex-directeur Ops — 200 restaurants managés, 3 enseignes digitalisées de A à Z",
      "Réseau de 40+ directeurs de chaînes HoReCa et franchise France",
      "-18% de coûts opérationnels obtenus sur la dernière enseigne gérée",
    ],
    skills: ["Ops Management", "Partenariats B2B", "Retail", "Restauration", "Franchise"],
    agencyStage: "Idée / recherche d'associé",
    lookingFor: "Un développeur IA capable de créer des solutions d'optimisation des stocks, menus et staffing pour le secteur HoReCa.",
    isVerified: true,
  },
  {
    id: "9",
    type: "tech",
    name: "Adrien P.",
    role: "Fondateur Tech",
    avatar: "AP",
    location: "Lille, France",
    bio: "Lead dev backend 7 ans, passionné d'automatisation. J'ai déployé des agents IA autonomes pour automatiser des workflows complexes en entreprise. Maîtrise parfaite de n8n, Make et des architectures multi-agents.",
    bullets: [
      "Lead dev backend 7 ans — spécialiste agents IA et automatisation n8n/LangGraph",
      "15 workflows d'automatisation déployés chez des clients, 200h/mois économisées",
      "Formation Make Advanced + certifié n8n Expert Partner",
    ],
    skills: ["Agents IA", "n8n", "Make/Zapier", "API Integration", "Automation", "LangGraph"],
    agencyName: "AutoFlow",
    agencyDescription: "Automatisation des workflows par agents IA",
    agencyStage: "Premiers clients",
    lookingFor: "Un commercial ou business developer pour closer les prospects. J'ai des démos très convaincantes, il faut quelqu'un pour amener les leads.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "10",
    type: "business",
    name: "Clara B.",
    role: "Fondatrice Business",
    avatar: "CB",
    location: "Paris, France",
    bio: "Avocate reconvertie en entrepreneur, 4 ans dans la LegalTech. J'ai co-fondé un SaaS contractuel vendu à 800k€. Je veux maintenant construire une agence IA spécialisée dans l'automatisation juridique et compliance.",
    bullets: [
      "Avocate reconvertie — co-fondatrice SaaS LegalTech revendu 800k€ en 3 ans",
      "Réseau de 60+ cabinets d'avocats et directions juridiques grands comptes",
      "+45% de taux de conversion obtenu sur le pipeline commercial LegalTech",
    ],
    skills: ["Droit des affaires", "LegalTech", "Business Development", "SaaS", "Fundraising"],
    agencyName: "LexIA",
    agencyDescription: "Automatisation juridique et compliance par l'IA",
    agencyStage: "Pré-seed / amorçage",
    lookingFor: "Un ingénieur IA avec expérience en NLP et traitement de documents légaux (contrats, réglementations).",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "11",
    type: "tech",
    name: "Youssef A.",
    role: "Fondateur Tech",
    avatar: "YA",
    location: "Paris, France",
    bio: "CTO de startup pendant 4 ans, full-stack et IA. J'ai construit de A à Z une plateforme SaaS IA utilisée par 500+ entreprises. Expert en architectures scalables et intégration LLMs en production.",
    bullets: [
      "CTO 4 ans — SaaS IA livré de zéro à 500+ entreprises clientes",
      "Stack complète : LLMs, Next.js, PostgreSQL, Docker, déploiement prod scalable",
      "Formation Stanford ML + certification AWS Solutions Architect",
    ],
    skills: ["CTO Experience", "LLMs", "Next.js", "PostgreSQL", "Docker", "Scalability"],
    agencyName: "BuildAI",
    agencyDescription: "Développement sur-mesure de produits IA pour startups et scale-ups",
    agencyStage: "Actif / cherche associé",
    lookingFor: "Un co-fondateur business avec expérience dans les startups tech pour gérer la croissance et lever des fonds.",
    linkedin: "#",
    isVerified: true,
  },
  {
    id: "12",
    type: "business",
    name: "Lucie G.",
    role: "Fondatrice Business",
    avatar: "LG",
    location: "Bordeaux, France",
    bio: "10 ans en cabinet de conseil (Capgemini), spécialisée transformation digitale des collectivités et du secteur public. Je vois une opportunité énorme dans l'IA pour le secteur public français.",
    bullets: [
      "10 ans Capgemini — projets à +5M€ pour collectivités et ministères",
      "Réseau de 25+ DSI et élus dans l'écosystème public français",
      "3 appels d'offres remportés seule sur les 6 derniers mois d'activité",
    ],
    skills: ["Secteur Public", "Conseil en transformation", "Appels d'offres", "Gestion de projet"],
    agencyStage: "Idée / en exploration",
    lookingFor: "Un expert IA capable de répondre aux enjeux de souveraineté numérique et de déployer des solutions IA on-premise pour administrations.",
    isVerified: true,
  },
];
